### ISSUE TITLE
Leaked passwords in the logs

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-community/bosh_exporter#2]
According to https://github.com/cloudfoundry/bosh-cli/issues/38, passwords might be leaked into the logs files. Upgrade the vendored bosh-cli libraries when the fix is available.

/cc @mkuratczyk

**Comment by mkuratczyk** [comment]
According to https://github.com/cloudfoundry/bosh-cli/issues/38#issuecomment-259185080 this has now been fixed in bosh cli

**Comment by frodenas** [comment]
Fixed at [v1.0.1](https://github.com/cloudfoundry-community/bosh_exporter/releases/tag/v1.0.1).
